### ISSUE TITLE
throw err cannot find module ./dist/index.js

### ISSUE THREAD

**Issue by ArisBee** [Setfive/cloudwatch-autowatch#1]
Hi,

I installed the requirements via npm and I'm in the project directory where index.js and package.json are located, but it throws the following error:

```bash
[ec2-user@Instance cloudwatch-autowatch]$ ./index.js --action=listSnsTopics
module.js:478
    throw err;
    ^

Error: Cannot find module './dist/index.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/cloudwatch-autowatch/index.js:2:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

Could you please provide me the exact npm and nodejs version you used while I'm troubleshooting? (I'm not yet a nodejs guru though )

**Comment by adatta02** [comment]
Whoops, sorry about that! The git repo was missing the checked in built JavaScript files.

If you "git pull" and re-run it should be good to go.

**Comment by ArisBee** [comment]
Yes, it was indeed a missing folder, it works well now.
Thanks,
